# Generated by Django 4.1.6 on 2023-02-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
                ("schedule_date", models.DateTimeField()),
            ],
        ),
    ]
